### ISSUE TITLE
thruster stacking inconsistency

### ISSUE THREAD

**Issue by bitzad** [Eggs-D-Studios/wos-issues#401]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

   i saw that thruster stacking was supposed to be fixed and i expected the speed to add up just like rockets(_2 rockets at 100 propulsion would yield 500 speed_) or ionrockets(_2 of them at 100 would yield 200_) would just like during pre wipe of august 2024 or the first weeks after wipe before vehicleseats got "wingardium leviosa'd" and propulsion systems and assembly propulsion had to temporarily be substituted by a diffrent method. 

   I first test with one thruster with dimensions 16 cubed and propulsion of 100(_((16*16*5)*0.0125+1)*100/10 = 500_) and it was as expected 
![Screenshot 2024-09-13 173148](https://github.com/user-attachments/assets/a0d5a1e1-eb73-4499-8a74-ea33c0345172)

however, whence it came to stacking them things started to get a bit weird

### How can we reproduce this bug?

1. build a simple ship with (3) thrusters and power, add a vehicle seat and a supplemental anchor with keybinds. here is mine:
![Screenshot 2024-09-13 173747](https://github.com/user-attachments/assets/905ec4bc-16c6-45ba-8ac9-aa270f0aaca3)

2. place two thrusters with same propulsion config(for some reason it doesnt stack if it is like this even if the diffrence is around 7.5) and make sure the resultant propulsion is not over 500
![Screenshot 2024-09-13 173255](https://github.com/user-attachments/assets/f711a4e9-e930-4100-a39b-c7771699c3f2)
this is the result of me using two thrusters both with dimensions {8,8, 30} which should produce 500 speed when both are working and are set to 100 propulsion ((8*8*30)*0.0125+1)*100/10) * 2 = 250 * 2 = 500

althou i have managed to somewhat stack them if one of them is set to a propulsion of 95
![Screenshot 2024-09-13 173654](https://github.com/user-attachments/assets/500cbbdc-e03f-4ac3-9cc2-b3d465227426)

things get a bit more inconsistent above 2 thrusters

### Frequency

Always

**Comment by Hexcede** [comment]
Vehicle seats weren't changed, nor was propulsion, the issues with them were just fixed. Additionally, for rockets to stack, they must be powered. It's possible the issue that you're experiencing is just due to the revert to the hammer code changes from before, which fixed a connection caching bug, that bug is temporarily back until I improve the `:MakeJoints()` code and can restore the changes from that branch.

**Comment by bitzad** [comment]
i still cant get the thrusters to properly stack when both of their configuration is the same, power is definitely going to both thruster, each thrusters manage to create propulsion on their own, when using both thrusters at the same time i managed to get them to stack just as how i reported it in the bug(only when configuration between them is far enough apart), more than 2 thrusters are still inconsistent. thou this shouldnt be a high priority bug i can always use ionrockets or rockets

**Comment by bitzad** [comment]
in the current update it does not stack at all

**Comment by bitzad** [comment]
its fixed now
