### ISSUE TITLE
Hide region name when RegionCloaker enabled

### ISSUE THREAD

**Issue by thecreare** [Eggs-D-Studios/wos-issues#935]
### Checklist

- [x] Do a quick check for similar/duplicate suggestions to reply under instead
- [x] Make sure your suggestion primarily focuses on making improvements
- [x] Have a good explanation for how the problem you're trying to solve is important

### Topic

A design problem (e.g. clunky UX, a balancing issue, etc)

### What problem are you focusing on, or what are you looking to improve?

Currently, RegionCloakers do not hide the planet name. This makes them useless with public universe databases that map planet names to coordinates. In space regions, the "region name" contains some encoding of the coordinates that can be decoded.

### What do you have in mind, if anything?

RegionCloakers should hide the planet name/region name in addition to the coordinates.

### Why is your proposal a good idea, if you had one?

These changes would make RegionCloakers useful

**Comment by thecreare** [comment]
Coordinates & names of region-cloaked regions are also currently shown in the menu

**Comment by mawesome4ever** [comment]
This should be fixed... I'll have to double check though

**Comment by thecreare** [comment]
I've just checked with a powered region cloaker at both my station and a planet base. All region names (planet names and deep space region "names") are still shown both in game and in the menu
